package symbols

// NTs is the type of a list of nonterminals
type NTs []NT

// Count of all nonterminals. (Values may be reconstructed by typecast)
const NumNTs = 3

// Gets the set of nonterminals that another nonterminal may start with.
// Can be used to build a topological sort of nonterminals in any 
// well-formed PEG grammar
func (nt NT) StartsWith() NTs {
	return startsWith[nt]
}

// "FIRST" set for nonterminals; would be generated by parser-generator
var startsWith = map[NT]NTs {
	NT_AxBC: NTs { NT_AorB, NT_As },
	NT_AorB: NTs { NT_As },
	NT_As: NTs {},
}