[package]
name = "g1"
version = "0.1.0"
authors = ["Marius Ackerman <goccmack@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
