
// Package symbols is generated by gogll. Do not edit.
package symbols

type Symbol interface{
	isSymbol()
	IsNonTerminal() bool
	String() string
}

func (NT) isSymbol() {}
func (T) isSymbol() {}

// NT is the type of non-terminals symbols
type NT int
const( 
	NT_Content NT = iota
	NT_Parens 
	NT_ParensOrChar 
	NT_String 
)

// T is the type of terminals symbols
type T int
const( 
	T_0 T = iota // char 
	T_1  // close 
	T_2  // open 
)

type Symbols []Symbol

func (ss Symbols) Strings() []string {
	strs := make([]string, len(ss))
	for i, s := range ss {
		strs[i] = s.String()
	}
	return strs
}

func (NT) IsNonTerminal() bool {
	return true
}

func (T) IsNonTerminal() bool {
	return false
}

func (nt NT) String() string {
	return ntToString[nt]
}

func (t T) String() string {
	return tToString[t]
}

var ntToString = []string { 
	"Content", /* NT_Content */
	"Parens", /* NT_Parens */
	"ParensOrChar", /* NT_ParensOrChar */
	"String", /* NT_String */ 
}

var tToString = []string { 
	"char", /* T_0 */
	"close", /* T_1 */
	"open", /* T_2 */ 
}

var stringNT = map[string]NT{ 
	"Content":NT_Content,
	"Parens":NT_Parens,
	"ParensOrChar":NT_ParensOrChar,
	"String":NT_String,
}
