// Package parser is generated by gogll. Do not edit.
package parser

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"ident/lexer"
	"ident/parser/bsr"
	"ident/parser/slot"
	"ident/parser/symbols"
	"ident/token"
)

type parser struct {
	cI int

	R *descriptors
	U *descriptors

	popped   map[poppedNode]bool
	crf_m    map[clusterNode][]*crfNode
	crf_f    map[clusterNode][]*crfNode
	crfNodes map[crfNode]*crfNode

	lex         *lexer.Lexer
	parseErrors []*Error

	bsrSet *bsr.Set
}

// index used for non-matches
const failInd = -1

func newParser(l *lexer.Lexer) *parser {
	return &parser{
		cI:     0,
		lex:    l,
		R:      &descriptors{},
		U:      &descriptors{},
		popped: make(map[poppedNode]bool),
		crf_m: map[clusterNode][]*crfNode{
			{symbols.NT_Ident, 0}: {},
		},
		crf_f:       map[clusterNode][]*crfNode{},
		crfNodes:    map[crfNode]*crfNode{},
		bsrSet:      bsr.New(symbols.NT_Ident, l),
		parseErrors: nil,
	}
}

// Parse returns the BSR set containing the parse forest.
// If the parse was successfull []*Error is nil
func Parse(l *lexer.Lexer) (*bsr.Set, []*Error) {
	return newParser(l).parse()
}

const lastSlot slot.Label = 14

const (
	_ slot.Label = iota + lastSlot

	fail_Ident
	fail_Keyword
	pass_Keyword1R0
)

func (p *parser) parse() (*bsr.Set, []*Error) {
	var L slot.Label
	m, cU := len(p.lex.Tokens)-1, 0
	p.ntAdd(symbols.NT_Ident, 0)
	// p.DumpDescriptors()
	for !p.R.empty() {
		L, cU, p.cI = p.R.remove()

		// fmt.Println()
		// fmt.Printf("L:%s, cI:%d, I[p.cI]:%s, cU:%d\n", L, p.cI, p.lex.Tokens[p.cI], cU)
		// p.DumpDescriptors()

		for {
			switch L {
			case slot.Ident0R0: // Ident : ∙!Keyword idChar RepidChar0x

				if !p.testSelect(slot.Ident0R0) {
					p.parseError(slot.Ident0R0, p.cI, first[slot.Ident0R0])
					L, p.cI = fail_Ident, cU
					goto nextSlot
				}
				p.call(fail_Ident, slot.Ident0R1, symbols.NT_Keyword, cU, p.cI)
			case slot.Ident0R1: // Ident : !Keyword ∙idChar RepidChar0x

				if !p.testSelect(slot.Ident0R1) {
					p.parseError(slot.Ident0R1, p.cI, first[slot.Ident0R1])
					L, p.cI = fail_Ident, cU
					goto nextSlot
				}
				p.bsrSet.Add(slot.Ident0R2, cU, p.cI, p.cI+1)
				p.cI++
				if !p.testSelect(slot.Ident0R2) {
					p.parseError(slot.Ident0R2, p.cI, first[slot.Ident0R2])
					L, p.cI = fail_Ident, cU
					goto nextSlot
				}
				p.call(slot.Ident0R3, fail_Ident, symbols.NT_RepidChar0x, cU, p.cI)
			case slot.Ident0R3: // Ident : !Keyword idChar RepidChar0x ∙

				p.rtn(symbols.NT_Ident, cU, p.cI)
			case fail_Ident: // Ident failure case
				p.rtn(symbols.NT_Ident, cU, failInd)
			case slot.Keyword0R0: // Keyword : ∙i f

				if !p.testSelect(slot.Keyword0R0) {
					p.parseError(slot.Keyword0R0, p.cI, first[slot.Keyword0R0])
					L, p.cI = slot.Keyword1R0, cU
					goto nextSlot
				}
				p.bsrSet.Add(slot.Keyword0R1, cU, p.cI, p.cI+1)
				p.cI++
				p.rtn(symbols.NT_Keyword, cU, p.cI)
				L, p.cI = pass_Keyword1R0, cU
				goto nextSlot
				if !p.testSelect(slot.Keyword0R1) {
					p.parseError(slot.Keyword0R1, p.cI, first[slot.Keyword0R1])
					L, p.cI = slot.Keyword1R0, cU
					goto nextSlot
				}
				p.bsrSet.Add(slot.Keyword0R2, cU, p.cI, p.cI+1)
				p.cI++
				p.rtn(symbols.NT_Keyword, cU, p.cI)
				L, p.cI = pass_Keyword1R0, cU
				goto nextSlot

			case slot.Keyword1R0: // Keyword : ∙f o r

				if !p.testSelect(slot.Keyword1R0) {
					p.parseError(slot.Keyword1R0, p.cI, first[slot.Keyword1R0])
					L, p.cI = fail_Keyword, cU
					goto nextSlot
				}
				p.bsrSet.Add(slot.Keyword1R1, cU, p.cI, p.cI+1)
				p.cI++
				p.rtn(symbols.NT_Keyword, cU, p.cI)

				if !p.testSelect(slot.Keyword1R1) {
					p.parseError(slot.Keyword1R1, p.cI, first[slot.Keyword1R1])
					L, p.cI = fail_Keyword, cU
					goto nextSlot
				}
				p.bsrSet.Add(slot.Keyword1R2, cU, p.cI, p.cI+1)
				p.cI++
				p.rtn(symbols.NT_Keyword, cU, p.cI)

				if !p.testSelect(slot.Keyword1R2) {
					p.parseError(slot.Keyword1R2, p.cI, first[slot.Keyword1R2])
					L, p.cI = fail_Keyword, cU
					goto nextSlot
				}
				p.bsrSet.Add(slot.Keyword1R3, cU, p.cI, p.cI+1)
				p.cI++
				p.rtn(symbols.NT_Keyword, cU, p.cI)

			case pass_Keyword1R0: // Keyword : ∙f o r

				if !p.testSelect(slot.Keyword1R0) {
					p.parseError(slot.Keyword1R0, p.cI, first[slot.Keyword1R0])

				}
				p.bsrSet.Add(slot.Keyword1R1, cU, p.cI, p.cI+1)
				p.cI++
				p.rtn(symbols.NT_Keyword, cU, p.cI)

				if !p.testSelect(slot.Keyword1R1) {
					p.parseError(slot.Keyword1R1, p.cI, first[slot.Keyword1R1])

				}
				p.bsrSet.Add(slot.Keyword1R2, cU, p.cI, p.cI+1)
				p.cI++
				p.rtn(symbols.NT_Keyword, cU, p.cI)

				if !p.testSelect(slot.Keyword1R2) {
					p.parseError(slot.Keyword1R2, p.cI, first[slot.Keyword1R2])

				}
				p.bsrSet.Add(slot.Keyword1R3, cU, p.cI, p.cI+1)
				p.cI++
				p.rtn(symbols.NT_Keyword, cU, p.cI)

			case fail_Keyword: // Keyword failure case
				p.rtn(symbols.NT_Keyword, cU, failInd)
			case slot.RepidChar0x0R0: // RepidChar0x : ∙idChar RepidChar0x

				if !p.testSelect(slot.RepidChar0x0R0) {
					p.parseError(slot.RepidChar0x0R0, p.cI, first[slot.RepidChar0x0R0])
					L, p.cI = slot.RepidChar0x1R0, cU
					goto nextSlot
				}
				p.bsrSet.Add(slot.RepidChar0x0R1, cU, p.cI, p.cI+1)
				p.cI++
				if !p.testSelect(slot.RepidChar0x0R1) {
					p.parseError(slot.RepidChar0x0R1, p.cI, first[slot.RepidChar0x0R1])
					L, p.cI = slot.RepidChar0x1R0, cU
					goto nextSlot
				}
				p.call(slot.RepidChar0x0R2, slot.RepidChar0x1R0, symbols.NT_RepidChar0x, cU, p.cI)
			case slot.RepidChar0x0R2: // RepidChar0x : idChar RepidChar0x ∙

				p.rtn(symbols.NT_RepidChar0x, cU, p.cI)
			case slot.RepidChar0x1R0: // RepidChar0x : ∙
				p.bsrSet.AddEmpty(slot.RepidChar0x1R0, p.cI)
				p.rtn(symbols.NT_RepidChar0x, cU, p.cI)

			default:
				panic("This must not happen")
			}
			// if exit switch normally, also exit loop and proceed to next
			// descriptor; if exit with goto nextSlot, repeat switch at next
			// slot
			break
		nextSlot:
		}
	}
	if !p.bsrSet.Contain(symbols.NT_Ident, 0, m) {
		p.sortParseErrors()
		return nil, p.parseErrors
	}
	return p.bsrSet, nil
}

func (p *parser) ntAdd(nt symbols.NT, j int) {
	l := slot.GetAlternates(nt)[0]
	p.dscAdd(l, j, j)
}

/*** Call Return Forest ***/

type poppedNode struct {
	X    symbols.NT
	k, j int
}

type clusterNode struct {
	X symbols.NT
	k int
}

type crfNode struct {
	L slot.Label
	i int
}

func (p *parser) call(Lm, Lf slot.Label, X symbols.NT, i, j int) {
	// fmt.Printf("p.call(%s,%d,%d)\n", L,i,j)
	um, exist := p.crfNodes[crfNode{Lm, i}]
	// fmt.Printf("  u exist=%t\n", exist)
	if !exist {
		um = &crfNode{Lm, i}
		p.crfNodes[*um] = um
	}
	uf, exist := p.crfNodes[crfNode{Lf, i}]
	if !exist {
		uf = &crfNode{Lf, i}
		p.crfNodes[*uf] = uf
	}

	ndV := clusterNode{X, j}
	vm, existm := p.crf_m[ndV]
	vf, existf := p.crf_f[ndV]
	if !existm && !existf {
		// fmt.Println("  v !exist")
		p.crf_m[ndV] = []*crfNode{um}
		p.crf_f[ndV] = []*crfNode{uf}
		p.ntAdd(X, j)
	} else {
		// fmt.Println("  v exist")
		if !existEdge(vm, um) {
			// fmt.Printf("  !existEdge(%v)\n", u)
			p.crf_m[ndV] = append(vm, um)
			// fmt.Printf("|popped|=%d\n", len(popped))
			for pnd := range p.popped {
				if pnd.X == X && pnd.k == j && pnd.j != failInd {
					p.addMatch(Lm, i, j, pnd.j)
				}
			}
		}
		if !existEdge(vf, uf) {
			p.crf_f[ndV] = append(vf, uf)
			for pnd := range p.popped {
				if pnd.X == X && pnd.k == j && pnd.j == failInd {
					p.addFail(Lf, i, j)
				}
			}
		}
	}
}

func existEdge(nds []*crfNode, nd *crfNode) bool {
	for _, nd1 := range nds {
		if nd1 == nd {
			return true
		}
	}
	return false
}

func (p *parser) rtn(X symbols.NT, k, j int) {
	// fmt.Printf("p.rtn(%s,%d,%d)\n", X,k,j)
	pn := poppedNode{X, k, j}
	if _, exist := p.popped[pn]; !exist {
		p.popped[pn] = true
		if j != failInd {
			for _, nd := range p.crf_m[clusterNode{X, k}] {
				p.addMatch(nd.L, nd.i, k, j)
			}
		} else {
			for _, nd := range p.crf_f[clusterNode{X, k}] {
				p.addFail(nd.L, nd.i, k)
			}
		}
	}
}

func (p *parser) addMatch(L slot.Label, i, k, j int) {
	p.bsrSet.Add(L, i, k, j)
	if isLookahead(L) {
		p.dscAdd(L, i, k)
	} else {
		p.dscAdd(L, i, j)
	}
}

func (p *parser) addFail(L slot.Label, i, k int) {
	if isLookahead(L) {
		p.dscAdd(L, i, k)
	} else {
		p.dscAdd(L, i, i)
	}
}

func isLookahead(L slot.Label) bool {
	return L <= lastSlot && L.IsLookahead()
}

// func CRFString() string {
// 	buf := new(bytes.Buffer)
// 	buf.WriteString("CRF: {")
// 	for cn, nds := range crf{
// 		for _, nd := range nds {
// 			fmt.Fprintf(buf, "%s->%s, ", cn, nd)
// 		}
// 	}
// 	buf.WriteString("}")
// 	return buf.String()
// }

func (cn clusterNode) String() string {
	return fmt.Sprintf("(%s,%d)", cn.X, cn.k)
}

func (n crfNode) String() string {
	return fmt.Sprintf("(%s,%d)", n.L.String(), n.i)
}

// func PoppedString() string {
// 	buf := new(bytes.Buffer)
// 	buf.WriteString("Popped: {")
// 	for p, _ := range popped {
// 		fmt.Fprintf(buf, "(%s,%d,%d) ", p.X, p.k, p.j)
// 	}
// 	buf.WriteString("}")
// 	return buf.String()
// }

/*** descriptors ***/

type descriptors struct {
	set []*descriptor
}

func (ds *descriptors) contain(d *descriptor) bool {
	for _, d1 := range ds.set {
		if d1 == d {
			return true
		}
	}
	return false
}

func (ds *descriptors) empty() bool {
	return len(ds.set) == 0
}

func (ds *descriptors) String() string {
	buf := new(bytes.Buffer)
	buf.WriteString("{")
	for i, d := range ds.set {
		if i > 0 {
			buf.WriteString("; ")
		}
		fmt.Fprintf(buf, "%s", d)
	}
	buf.WriteString("}")
	return buf.String()
}

type descriptor struct {
	L slot.Label
	k int
	i int
}

func (d *descriptor) String() string {
	return fmt.Sprintf("%s,%d,%d", d.L, d.k, d.i)
}

func (p *parser) dscAdd(L slot.Label, k, i int) {
	// fmt.Printf("p.dscAdd(%s,%d,%d)\n", L, k, i)
	d := &descriptor{L, k, i}
	if !p.U.contain(d) {
		p.R.set = append(p.R.set, d)
		p.U.set = append(p.U.set, d)
	}
}

func (ds *descriptors) remove() (L slot.Label, k, i int) {
	d := ds.set[len(ds.set)-1]
	ds.set = ds.set[:len(ds.set)-1]
	// fmt.Printf("remove: %s,%d,%d\n", d.L, d.k, d.i)
	return d.L, d.k, d.i
}

func (p *parser) DumpDescriptors() {
	p.DumpR()
	p.DumpU()
}

func (p *parser) DumpR() {
	fmt.Println("R:")
	for _, d := range p.R.set {
		fmt.Printf(" %s\n", d)
	}
}

func (p *parser) DumpU() {
	fmt.Println("U:")
	for _, d := range p.U.set {
		fmt.Printf(" %s\n", d)
	}
}

/*** TestSelect ***/

func (p *parser) follow(nt symbols.NT) bool {
	_, exist := followSets[nt][p.lex.Tokens[p.cI].Type()]
	return exist
}

func (p *parser) testSelect(l slot.Label) bool {
	return l.IsNullable() || l.FirstContains(p.lex.Tokens[p.cI].Type())
	// _, exist := first[l][p.lex.Tokens[p.cI].Type()]
	// return exist
}

var first = []map[token.Type]string{
	// Ident : ∙!Keyword idChar RepidChar0x
	{
		token.T_2: "idChar",
	},
	// Ident : !Keyword ∙idChar RepidChar0x
	{
		token.T_2: "idChar",
	},
	// Ident : !Keyword idChar ∙RepidChar0x
	{
		token.EOF: "$",
		token.T_2: "idChar",
	},
	// Ident : !Keyword idChar RepidChar0x ∙
	{
		token.EOF: "$",
	},
	// Keyword : ∙i f
	{
		token.T_1: "i",
	},
	// Keyword : i ∙f
	{
		token.T_0: "f",
	},
	// Keyword : i f ∙
	{
		token.EOF: "$",
	},
	// Keyword : ∙f o r
	{
		token.T_0: "f",
	},
	// Keyword : f ∙o r
	{
		token.T_3: "o",
	},
	// Keyword : f o ∙r
	{
		token.T_4: "r",
	},
	// Keyword : f o r ∙
	{
		token.EOF: "$",
	},
	// RepidChar0x : ∙idChar RepidChar0x
	{
		token.T_2: "idChar",
	},
	// RepidChar0x : idChar ∙RepidChar0x
	{
		token.EOF: "$",
		token.T_2: "idChar",
	},
	// RepidChar0x : idChar RepidChar0x ∙
	{
		token.EOF: "$",
	},
	// RepidChar0x : ∙
	{
		token.EOF: "$",
	},
}

var followSets = []map[token.Type]string{
	// Ident
	{
		token.EOF: "$",
	},
	// Keyword
	{
		token.EOF: "$",
	},
	// RepidChar0x
	{
		token.EOF: "$",
	},
}

/*** Errors ***/

/*
Error is returned by Parse at every point at which the parser fails to parse
a grammar production. For non-LL-1 grammars there will be an error for each
alternate attempted by the parser.

The errors are sorted in descending order of input position (index of token in
the stream of tokens).

Normally the error of interest is the one that has parsed the largest number of
tokens.
*/
type Error struct {
	// Index of token that caused the error.
	cI int

	// Grammar slot at which the error occured.
	Slot slot.Label

	// The token at which the error occurred.
	Token *token.Token

	// The line and column in the input text at which the error occurred
	Line, Column int

	// The tokens expected at the point where the error occurred
	Expected map[token.Type]string
}

func (pe *Error) String() string {
	w := new(bytes.Buffer)
	fmt.Fprintf(w, "Parse Error: %s I[%d]=%s at line %d col %d\n",
		pe.Slot, pe.cI, pe.Token, pe.Line, pe.Column)
	exp := []string{}
	for _, e := range pe.Expected {
		exp = append(exp, e)
	}
	fmt.Fprintf(w, "Expected one of: [%s]", strings.Join(exp, ","))
	return w.String()
}

func (p *parser) parseError(slot slot.Label, i int, expected map[token.Type]string) {
	pe := &Error{cI: i, Slot: slot, Token: p.lex.Tokens[i], Expected: expected}
	p.parseErrors = append(p.parseErrors, pe)
}

func (p *parser) sortParseErrors() {
	sort.Slice(p.parseErrors,
		func(i, j int) bool {
			return p.parseErrors[j].Token.Lext() < p.parseErrors[i].Token.Lext()
		})
	for _, pe := range p.parseErrors {
		pe.Line, pe.Column = p.lex.GetLineColumn(pe.Token.Lext())
	}
}
