
// Package symbols is generated by gogll. Do not edit.
package symbols

type Symbol interface{
	isSymbol()
	IsNonTerminal() bool
	String() string
}

func (NT) isSymbol() {}
func (T) isSymbol() {}

// NT is the type of non-terminals symbols
type NT int
const( 
	NT_Base NT = iota
	NT_Optional 
	NT_Required 
	NT_S1 
)

const NumNTs = 4

type NTs []NT

// T is the type of terminals symbols
type T int
const( 
	T_0 T = iota // Base 
	T_1  // Required 
)

type Symbols []Symbol

func (ss Symbols) Strings() []string {
	strs := make([]string, len(ss))
	for i, s := range ss {
		strs[i] = s.String()
	}
	return strs
}

func (NT) IsNonTerminal() bool {
	return true
}

func (T) IsNonTerminal() bool {
	return false
}

func (nt NT) String() string {
	return ntToString[nt]
}

func (t T) String() string {
	return tToString[t]
}

func (nt NT) LeftRec() NTs {
	return leftRec[nt]
}

func (nt NT) IsOrdered() bool {
	return ordered[nt]
}

var ntToString = []string { 
	"Base", /* NT_Base */
	"Optional", /* NT_Optional */
	"Required", /* NT_Required */
	"S1", /* NT_S1 */ 
}

var tToString = []string { 
	"Base", /* T_0 */
	"Required", /* T_1 */ 
}

var stringNT = map[string]NT{ 
	"Base":NT_Base,
	"Optional":NT_Optional,
	"Required":NT_Required,
	"S1":NT_S1,
}

var leftRec = map[NT]NTs { 
	NT_Base: NTs {  },
	NT_Optional: NTs {  },
	NT_Required: NTs {  },
	NT_S1: NTs {  NT_Required,  },
}

var ordered = map[NT]bool { 
}
