
// Package symbols is generated by gogll. Do not edit.
package symbols

type Symbol interface{
	isSymbol()
	IsNonTerminal() bool
	String() string
}

func (NT) isSymbol() {}
func (T) isSymbol() {}

// NT is the type of non-terminals symbols
type NT int
const( 
	NT_ATT_VALUE NT = iota
	NT_Attribute 
	NT_CHAR_REF 
	NT_COMMENT 
	NT_ComEnterior 
	NT_ComStart 
	NT_Content 
	NT_ContentAlts 
	NT_Document 
	NT_DubCondClose 
	NT_DubDash 
	NT_ENTITY_REF 
	NT_ElemCloseAlts 
	NT_Element 
	NT_EncName 
	NT_EncodingDecl 
	NT_Eq 
	NT_Hex 
	NT_HexAlts 
	NT_LetColonAlts 
	NT_LetDigSymAlts 
	NT_Misc 
	NT_NAME 
	NT_NAME_CHAR 
	NT_NameCharRep 
	NT_OptEncodDecl 
	NT_OptXMLDecl 
	NT_Prolog 
	NT_QuoEncNam 
	NT_QuoVerNum 
	NT_REFERENCE 
	NT_RepHexAlts0x 
	NT_RepLDSAlts0x 
	NT_RepMisc0x 
	NT_RepNameChar0x 
	NT_RepSAttx0x 
	NT_SAtt 
	NT_SinCondClose 
	NT_SymRefAlts 
	NT_VersionInfo 
	NT_VersionNum 
	NT_XMLDecl 
)

const NumNTs = 42

type NTs []NT

// T is the type of terminals symbols
type T int
const( 
	T_0 T = iota // & 
	T_1  // &# 
	T_2  // &#x 
	T_3  // -- 
	T_4  // ; 
	T_5  // aA_fF 
	T_6  // andCarrs 
	T_7  // angLBrk 
	T_8  // angRBrk 
	T_9  // charData 
	T_10  // col_ 
	T_11  // dot_BSlashDash 
	T_12  // dot_BSlashDashCol 
	T_13  // dubQu 
	T_14  // encoding 
	T_15  // eq 
	T_16  // exclamation 
	T_17  // let 
	T_18  // num 
	T_19  // optSpaceEsc 
	T_20  // repNum1x 
	T_21  // sinQu 
	T_22  // slashAngLBrk 
	T_23  // slashAngRBrk 
	T_24  // spaceEsc 
	T_25  // version 
	T_26  // xmlDeclEnd 
	T_27  // xmlDeclStart 
)

type Symbols []Symbol

func (ss Symbols) Strings() []string {
	strs := make([]string, len(ss))
	for i, s := range ss {
		strs[i] = s.String()
	}
	return strs
}

func (NT) IsNonTerminal() bool {
	return true
}

func (T) IsNonTerminal() bool {
	return false
}

func (nt NT) String() string {
	return ntToString[nt]
}

func (t T) String() string {
	return tToString[t]
}

func (nt NT) LeftRec() NTs {
	return leftRec[nt]
}

var ntToString = []string { 
	"ATT_VALUE", /* NT_ATT_VALUE */
	"Attribute", /* NT_Attribute */
	"CHAR_REF", /* NT_CHAR_REF */
	"COMMENT", /* NT_COMMENT */
	"ComEnterior", /* NT_ComEnterior */
	"ComStart", /* NT_ComStart */
	"Content", /* NT_Content */
	"ContentAlts", /* NT_ContentAlts */
	"Document", /* NT_Document */
	"DubCondClose", /* NT_DubCondClose */
	"DubDash", /* NT_DubDash */
	"ENTITY_REF", /* NT_ENTITY_REF */
	"ElemCloseAlts", /* NT_ElemCloseAlts */
	"Element", /* NT_Element */
	"EncName", /* NT_EncName */
	"EncodingDecl", /* NT_EncodingDecl */
	"Eq", /* NT_Eq */
	"Hex", /* NT_Hex */
	"HexAlts", /* NT_HexAlts */
	"LetColonAlts", /* NT_LetColonAlts */
	"LetDigSymAlts", /* NT_LetDigSymAlts */
	"Misc", /* NT_Misc */
	"NAME", /* NT_NAME */
	"NAME_CHAR", /* NT_NAME_CHAR */
	"NameCharRep", /* NT_NameCharRep */
	"OptEncodDecl", /* NT_OptEncodDecl */
	"OptXMLDecl", /* NT_OptXMLDecl */
	"Prolog", /* NT_Prolog */
	"QuoEncNam", /* NT_QuoEncNam */
	"QuoVerNum", /* NT_QuoVerNum */
	"REFERENCE", /* NT_REFERENCE */
	"RepHexAlts0x", /* NT_RepHexAlts0x */
	"RepLDSAlts0x", /* NT_RepLDSAlts0x */
	"RepMisc0x", /* NT_RepMisc0x */
	"RepNameChar0x", /* NT_RepNameChar0x */
	"RepSAttx0x", /* NT_RepSAttx0x */
	"SAtt", /* NT_SAtt */
	"SinCondClose", /* NT_SinCondClose */
	"SymRefAlts", /* NT_SymRefAlts */
	"VersionInfo", /* NT_VersionInfo */
	"VersionNum", /* NT_VersionNum */
	"XMLDecl", /* NT_XMLDecl */ 
}

var tToString = []string { 
	"&", /* T_0 */
	"&#", /* T_1 */
	"&#x", /* T_2 */
	"--", /* T_3 */
	";", /* T_4 */
	"aA_fF", /* T_5 */
	"andCarrs", /* T_6 */
	"angLBrk", /* T_7 */
	"angRBrk", /* T_8 */
	"charData", /* T_9 */
	"col_", /* T_10 */
	"dot_BSlashDash", /* T_11 */
	"dot_BSlashDashCol", /* T_12 */
	"dubQu", /* T_13 */
	"encoding", /* T_14 */
	"eq", /* T_15 */
	"exclamation", /* T_16 */
	"let", /* T_17 */
	"num", /* T_18 */
	"optSpaceEsc", /* T_19 */
	"repNum1x", /* T_20 */
	"sinQu", /* T_21 */
	"slashAngLBrk", /* T_22 */
	"slashAngRBrk", /* T_23 */
	"spaceEsc", /* T_24 */
	"version", /* T_25 */
	"xmlDeclEnd", /* T_26 */
	"xmlDeclStart", /* T_27 */ 
}

var stringNT = map[string]NT{ 
	"ATT_VALUE":NT_ATT_VALUE,
	"Attribute":NT_Attribute,
	"CHAR_REF":NT_CHAR_REF,
	"COMMENT":NT_COMMENT,
	"ComEnterior":NT_ComEnterior,
	"ComStart":NT_ComStart,
	"Content":NT_Content,
	"ContentAlts":NT_ContentAlts,
	"Document":NT_Document,
	"DubCondClose":NT_DubCondClose,
	"DubDash":NT_DubDash,
	"ENTITY_REF":NT_ENTITY_REF,
	"ElemCloseAlts":NT_ElemCloseAlts,
	"Element":NT_Element,
	"EncName":NT_EncName,
	"EncodingDecl":NT_EncodingDecl,
	"Eq":NT_Eq,
	"Hex":NT_Hex,
	"HexAlts":NT_HexAlts,
	"LetColonAlts":NT_LetColonAlts,
	"LetDigSymAlts":NT_LetDigSymAlts,
	"Misc":NT_Misc,
	"NAME":NT_NAME,
	"NAME_CHAR":NT_NAME_CHAR,
	"NameCharRep":NT_NameCharRep,
	"OptEncodDecl":NT_OptEncodDecl,
	"OptXMLDecl":NT_OptXMLDecl,
	"Prolog":NT_Prolog,
	"QuoEncNam":NT_QuoEncNam,
	"QuoVerNum":NT_QuoVerNum,
	"REFERENCE":NT_REFERENCE,
	"RepHexAlts0x":NT_RepHexAlts0x,
	"RepLDSAlts0x":NT_RepLDSAlts0x,
	"RepMisc0x":NT_RepMisc0x,
	"RepNameChar0x":NT_RepNameChar0x,
	"RepSAttx0x":NT_RepSAttx0x,
	"SAtt":NT_SAtt,
	"SinCondClose":NT_SinCondClose,
	"SymRefAlts":NT_SymRefAlts,
	"VersionInfo":NT_VersionInfo,
	"VersionNum":NT_VersionNum,
	"XMLDecl":NT_XMLDecl,
}

var leftRec = map[NT]NTs { 
	NT_ATT_VALUE: NTs {  },
	NT_Attribute: NTs {  NT_NAME,  NT_LetColonAlts,  },
	NT_CHAR_REF: NTs {  },
	NT_COMMENT: NTs {  NT_ComStart,  },
	NT_ComEnterior: NTs {  NT_DubDash,  },
	NT_ComStart: NTs {  },
	NT_Content: NTs {  NT_ComStart,  NT_Element,  NT_REFERENCE,  NT_ENTITY_REF,  NT_CHAR_REF,  NT_ContentAlts,  NT_COMMENT,  },
	NT_ContentAlts: NTs {  NT_ComStart,  NT_Element,  NT_REFERENCE,  NT_ENTITY_REF,  NT_CHAR_REF,  NT_COMMENT,  },
	NT_Document: NTs {  NT_Misc,  NT_COMMENT,  NT_ComStart,  NT_OptXMLDecl,  NT_XMLDecl,  NT_RepMisc0x,  NT_Element,  NT_Prolog,  },
	NT_DubCondClose: NTs {  NT_SymRefAlts,  NT_REFERENCE,  NT_ENTITY_REF,  NT_CHAR_REF,  },
	NT_DubDash: NTs {  },
	NT_ENTITY_REF: NTs {  },
	NT_ElemCloseAlts: NTs {  },
	NT_Element: NTs {  },
	NT_EncName: NTs {  },
	NT_EncodingDecl: NTs {  },
	NT_Eq: NTs {  },
	NT_Hex: NTs {  NT_HexAlts,  },
	NT_HexAlts: NTs {  },
	NT_LetColonAlts: NTs {  },
	NT_LetDigSymAlts: NTs {  },
	NT_Misc: NTs {  NT_COMMENT,  NT_ComStart,  },
	NT_NAME: NTs {  NT_LetColonAlts,  },
	NT_NAME_CHAR: NTs {  },
	NT_NameCharRep: NTs {  NT_NAME_CHAR,  },
	NT_OptEncodDecl: NTs {  NT_EncodingDecl,  },
	NT_OptXMLDecl: NTs {  NT_XMLDecl,  },
	NT_Prolog: NTs {  NT_XMLDecl,  NT_RepMisc0x,  NT_Misc,  NT_COMMENT,  NT_ComStart,  NT_OptXMLDecl,  },
	NT_QuoEncNam: NTs {  },
	NT_QuoVerNum: NTs {  },
	NT_REFERENCE: NTs {  NT_ENTITY_REF,  NT_CHAR_REF,  },
	NT_RepHexAlts0x: NTs {  NT_HexAlts,  },
	NT_RepLDSAlts0x: NTs {  NT_LetDigSymAlts,  },
	NT_RepMisc0x: NTs {  NT_Misc,  NT_COMMENT,  NT_ComStart,  },
	NT_RepNameChar0x: NTs {  NT_NAME_CHAR,  },
	NT_RepSAttx0x: NTs {  NT_SAtt,  },
	NT_SAtt: NTs {  },
	NT_SinCondClose: NTs {  NT_SymRefAlts,  NT_REFERENCE,  NT_ENTITY_REF,  NT_CHAR_REF,  },
	NT_SymRefAlts: NTs {  NT_ENTITY_REF,  NT_CHAR_REF,  NT_REFERENCE,  },
	NT_VersionInfo: NTs {  },
	NT_VersionNum: NTs {  NT_NAME_CHAR,  },
	NT_XMLDecl: NTs {  },
}
