
// Package symbols is generated by gogll. Do not edit.
package symbols

type Symbol interface{
	isSymbol()
	IsNonTerminal() bool
	String() string
}

func (NT) isSymbol() {}
func (T) isSymbol() {}

// NT is the type of non-terminals symbols
type NT int
const( 
	NT_EncName NT = iota
	NT_LetDigSymAlts 
	NT_LetDigSymAltsRepx0 
)

// T is the type of terminals symbols
type T int
const( 
	T_0 T = iota // anyDotDashEtc 
	T_1  // digit 
	T_2  // lets 
)

type Symbols []Symbol

func (ss Symbols) Strings() []string {
	strs := make([]string, len(ss))
	for i, s := range ss {
		strs[i] = s.String()
	}
	return strs
}

func (NT) IsNonTerminal() bool {
	return true
}

func (T) IsNonTerminal() bool {
	return false
}

func (nt NT) String() string {
	return ntToString[nt]
}

func (t T) String() string {
	return tToString[t]
}

var ntToString = []string { 
	"EncName", /* NT_EncName */
	"LetDigSymAlts", /* NT_LetDigSymAlts */
	"LetDigSymAltsRepx0", /* NT_LetDigSymAltsRepx0 */ 
}

var tToString = []string { 
	"anyDotDashEtc", /* T_0 */
	"digit", /* T_1 */
	"lets", /* T_2 */ 
}

var stringNT = map[string]NT{ 
	"EncName":NT_EncName,
	"LetDigSymAlts":NT_LetDigSymAlts,
	"LetDigSymAltsRepx0":NT_LetDigSymAltsRepx0,
}
